#!/usr/bin/env python3

CONFIG = {
    "name": "GPT-SoVITS 预训练模型",
    "repo": "XXXXRT/GPT-SoVITS-Pretrained",
    "file": "pretrained_models.zip",
    "env_var": "PRETRAINED_MODELS_PATH",
    "default_path": "GPT_SoVITS/pretrained_models",
    "temp_prefix": "PretrainedModels",
    "install_mode": "root_items",
    "strip_single_root": True,
    "managed_items": [
        "chinese-hubert-base",
        "chinese-roberta-wwm-ext-large",
        "fast_langdetect",
        "g2pw-chinese",
        "gsv-v2final-pretrained",
        "gsv-v4-pretrained",
        "models--nvidia--bigvgan_v2_24khz_100band_256x",
        "sv",
        "v2Pro",
        "s1bert25hz-2kh-longer-epoch=68e-step=50232.ckpt",
        "s1v3.ckpt",
        "s2D488k.pth",
        "s2G488k.pth",
        "s2Gv3.pth",
    ],
    "files": [
        "chinese-hubert-base",
        "chinese-roberta-wwm-ext-large",
        "gsv-v2final-pretrained",
        "gsv-v4-pretrained",
        "models--nvidia--bigvgan_v2_24khz_100band_256x",
        "sv",
        "v2Pro",
        "s1bert25hz-2kh-longer-epoch=68e-step=50232.ckpt",
        "s1v3.ckpt",
        "s2D488k.pth",
        "s2G488k.pth",
        "s2Gv3.pth",
    ],
}
